#!/bin/bash

source ./env.sh
set -e

# INPUTS: 
# - ${SAMPLE}_to_pfal.50MAPQ.sorted.bam
# OUTPUTS:

# - ${SAMPLE}_to_pfal_${THRESHOLD}.bed
# - ${SAMPLE}_to_pfal_${THRESHOLD}.log
# - ${SAMPLE}_to_pfal_${THRESHOLD}.${PERCENT_CUTOFF}p.${TYPE}.bed

# Define all sample names here
SAMPLES=("28C1" "28C2" "28K1" "28K2" "32C1" "32C2" "32K1" "32K2" "36C1" "36C2" "36K1" "36K2")

TYPES=("a" "m" "17802" "17596")  # m6A, m5C, pseudouridine, inosine
PERCENT_CUTOFF=0

OUTDIR=$(pwd)/02_generating_bedmethyls_output
mkdir -p ${OUTDIR}

# 0.65 coverage, specific for a 28C1 coverage plot
THRESHOLD=0.65
SAMPLE="28C1"
${MODKIT_PATH} pileup --filter-threshold ${THRESHOLD} ${FILTERED_BAMDIR}/${SAMPLE}_to_pfal.50MAPQ.sorted.bam ${OUTDIR}/${SAMPLE}_to_pfal_${THRESHOLD}.bed --log-filepath ${OUTDIR}/${SAMPLE}_to_pfal_${THRESHOLD}.log

for TYPE in "${TYPES[@]}"; do
    cat ${OUTDIR}/${SAMPLE}_to_pfal_${THRESHOLD}.bed | awk -v TYPE=$TYPE -v PERCENT_CUTOFF=$PERCENT_CUTOFF '{if ($4 == TYPE && $11 > PERCENT_CUTOFF) print $0 }' > ${OUTDIR}/${SAMPLE}_to_pfal_${THRESHOLD}.${PERCENT_CUTOFF}p.${TYPE}.bed
done


for SAMPLE in "${SAMPLES[@]}"; do
    echo "Processing ${SAMPLE}..."

    # Generating bedmethyls:
    THRESHOLD=0.95
    ${MODKIT_PATH} pileup --filter-threshold ${THRESHOLD} ${FILTERED_BAMDIR}/${SAMPLE}_to_pfal.50MAPQ.sorted.bam ${OUTDIR}/${SAMPLE}_to_pfal_${THRESHOLD}.bed --log-filepath ${OUTDIR}/${SAMPLE}_to_pfal_${THRESHOLD}.log
    
    for TYPE in "${TYPES[@]}"; do
        cat ${OUTDIR}/${SAMPLE}_to_pfal_${THRESHOLD}.bed | awk -v TYPE=$TYPE -v PERCENT_CUTOFF=$PERCENT_CUTOFF '{if ($4 == TYPE && $11 > PERCENT_CUTOFF) print $0 }' > ${OUTDIR}/${SAMPLE}_to_pfal_${THRESHOLD}.${PERCENT_CUTOFF}p.${TYPE}.bed
    done
done

# below command checks for INOSINES in protein coding genes
# awk '{if ($10 > 20 && $11 > 25) print $0}' ${OUTDIR}/28C1_to_pfal_0.65.0p.17596.bed | bedtools intersect -a stdin -b <(awk -F'\t' '$3=="protein_coding_gene"' ${ANNOTATION_FILE}) -u
# below command compares inosines detected in nanopore data with m6As detected in GLORI data
# awk '{if ($10 > 20 && $11 > 25) print $0}' ${OUTDIR}/28C1_to_pfal_0.65.0p.17596.bed | bedtools intersect -a stdin -b <(awk -F'\t' '$3=="protein_coding_gene"' ${ANNOTATION_FILE}) -u | bedtools window -a stdin -b 05_glori_x_nanopore_overlap_output/glori_12u24u48.bed -w 1 -sm
# below command identifies smeared m6As
# awk '{if ($10 > 20 && ($12/($10+$16+$17)*100) >= 50) print $0}' 02_generating_bedmethyls_output/28C1_to_pfal_0.95.0p.a.bed | sort -k1,1 -k2,2n -k6,6 | bedtools merge -s -d 1 -i stdin -c 6,1 -o distinct,count | awk '{if ($5 > 2) print $0}'

# NB where does ($12/($10+$16+$17)*100) come from? 10 is valid coverage, 16 is number of mods that failed the mod prob threshold, 17 is the number of non canonical base calls. You can see below how column 16 is probably mistakenly excluded from valid cov
#(base) jlevendis@UMD-V3H4VVH12M 01_m6A_3p_readthrough_analysis % grep 2336146 02_generating_bedmethyls_output/28C1_to_pfal_0.95.0p.a.bed                                                                                                                                                                       
#Pf3D7_14_v3     2336145 2336146 a       50      -       2336145 2336146 255,0,0 50      66.00   33      17      0       1048    39      0       0
#Pf3D7_14_v3     2336146 2336147 a       44      -       2336146 2336147 255,0,0 44      65.91   29      14      1       1001    95      0       0
#(base) jlevendis@UMD-V3H4VVH12M 01_m6A_3p_readthrough_analysis % grep 2336146 02_generating_bedmethyls_output/28C1_to_pfal_0.65.0p.a.bed
#Pf3D7_14_v3     2336145 2336146 a       77      -       2336145 2336146 255,0,0 77      61.04   47      30      0       1048    11      1       0
#Pf3D7_14_v3     2336146 2336147 a       113     -       2336146 2336147 255,0,0 113     52.21   59      53      1       1001    26      0       0
