#!/bin/bash

source ./env.sh
set -e

# INPUTS: 
# - ${SAMPLE}_to_pfal.50MAPQ.sorted.bam
# - ${ANNOTATION}

# OUTPUTS:
# - ${SAMPLE}_to_pfal.50MAPQ.sorted.bam.featureCounts
# - ${SAMPLE}_to_pfal.50MAPQ.sorted.bam.featureCounts



# Define all sample names here
SAMPLES=("28C1" "28C2" "28K1" "28K2" "32C1" "32C2" "32K1" "32K2" "36C1" "36C2" "36K1" "36K2")

THRESHOLD=0.95
TYPE="a" 
PERCENT_CUTOFF=0 

OUTDIR=$(pwd)/03_featureCounts_output
mkdir -p ${OUTDIR}

# Generating featureCounts:
${FEATURECOUNTS_PATH} -O -s 1 -L -R CORE -a ${ANNOTATION_FILE} -o ${OUTDIR} \
    ${FILTERED_BAMDIR}/28C1_to_pfal.50MAPQ.sorted.bam \
    ${FILTERED_BAMDIR}/28C2_to_pfal.50MAPQ.sorted.bam \
    ${FILTERED_BAMDIR}/28K1_to_pfal.50MAPQ.sorted.bam \
    ${FILTERED_BAMDIR}/28K2_to_pfal.50MAPQ.sorted.bam \
    ${FILTERED_BAMDIR}/32C1_to_pfal.50MAPQ.sorted.bam \
    ${FILTERED_BAMDIR}/32C2_to_pfal.50MAPQ.sorted.bam \
    ${FILTERED_BAMDIR}/32K1_to_pfal.50MAPQ.sorted.bam \
    ${FILTERED_BAMDIR}/32K2_to_pfal.50MAPQ.sorted.bam \
    ${FILTERED_BAMDIR}/36C1_to_pfal.50MAPQ.sorted.bam \
    ${FILTERED_BAMDIR}/36C2_to_pfal.50MAPQ.sorted.bam \
    ${FILTERED_BAMDIR}/36K1_to_pfal.50MAPQ.sorted.bam \
    ${FILTERED_BAMDIR}/36K2_to_pfal.50MAPQ.sorted.bam

mv *_to_pfal.50MAPQ.sorted.bam.featureCounts ${OUTDIR}/
mv subread_featureCounts_results ${OUTDIR}/
mv subread_featureCounts_results.summary ${OUTDIR}/

# From each featureCounts file the third column is number of assignments. We can filter for just entries with multiple assignments (>1) and get a list of gene ids that are involved in overlapping assignments. The below gives us a list of genes with the number of overlapping read counts:

for SAMPLE in "${SAMPLES[@]}"; do
    echo "Processing ${SAMPLE}..."

    awk '$3 > 1 {print $4}' ${OUTDIR}/${SAMPLE}_to_pfal.50MAPQ.sorted.bam.featureCounts | tr ',' '\n' > ${OUTDIR}/${SAMPLE}_overlaps.txt
    sort ${OUTDIR}/${SAMPLE}_overlaps.txt | uniq -c > ${OUTDIR}/${SAMPLE}_overlaps_counts.txt
done

# # There are 3 parent types of features in the Plasmodium off file: protein_coding_gene, ncRNA_gene, pseudogene. I'll create a list of all gene IDs with the following commands:
awk '$3=="protein_coding_gene" {split ($9,x,/[=;]/); print x[2]}' ${ANNOTATION_FILE} > ${OUTDIR}/pcg_pseudogene_ncRNA_list.tsv
awk '$3=="ncRNA_gene" {split ($9,x,/[=;]/); print x[2]}' ${ANNOTATION_FILE} >> ${OUTDIR}/pcg_pseudogene_ncRNA_list.tsv
awk '$3=="pseudogene" {split ($9,x,/[=;]/); print x[2]}' ${ANNOTATION_FILE} >> ${OUTDIR}/pcg_pseudogene_ncRNA_list.tsv
cp ${OUTDIR}/pcg_pseudogene_ncRNA_list.tsv ${OUTDIR}/combined_overlap_counts.txt

for SAMPLE in "${SAMPLES[@]}"; do
    echo "Processing ${SAMPLE}..."

    awk 'NR==FNR{a[$2]=$1;next} {if ($1 in a) {print $0"\t" a[$1]} else {print $0"\t"0}}' ${OUTDIR}/${SAMPLE}_overlaps_counts.txt ${OUTDIR}/combined_overlap_counts.txt > ${OUTDIR}/temp.txt && mv ${OUTDIR}/temp.txt ${OUTDIR}/combined_overlap_counts.txt
done

printf "Geneid\t28C1\t28C2\t28K1\t28K2\t32C1\t32C2\t32K1\t32K2\t36C1\t36C2\t36K1\t36K2\n" | cat - ${OUTDIR}/combined_overlap_counts.txt > ${OUTDIR}/tmp && mv ${OUTDIR}/tmp ${OUTDIR}/combined_overlap_counts.txt
