#!/bin/bash
set -e

source ./env.sh
source ${RQC_DIR}/env/bin/activate

# INPUTS: 
# - ${SAMPLE}_to_pfal.50MAPQ.sorted.bam
# - ${ANNOTATION}

# OUTPUTS:
# - ${TIMEPOINT}_mrna_tes_analysis_${TIMEPOINT}hpi.tsv
# - ${TIMEPOINT}_mRNA_methylation_analysis_${TIMEPOINT}hpi.tsv


PADDING=500
READ_DEPTH=10
M6A_RATIO=0.5
POLY_A_FILTER=10

OUTDIR=$(pwd)/04_tes_and_gene_methylation_analysis_output
mkdir -p ${OUTDIR}

TIMEPOINTS=("28" "32" "36")

for TIMEPOINT in "${TIMEPOINTS[@]}"; do
    echo "Processing ${TIMEPOINT}..."

    # Generating bedmethyls:
    # TES change analysis (WAM change analysis)
    # set up samples file
    rm -f ${OUTDIR}/${TIMEPOINT}_laptop_samples.txt
    touch ${OUTDIR}/${TIMEPOINT}_laptop_samples.txt
    echo "${TIMEPOINT}C1_read_depth control bam ${FILTERED_BAMDIR}/${TIMEPOINT}C1_to_pfal.50MAPQ.sorted.bam" >> ${OUTDIR}/${TIMEPOINT}_laptop_samples.txt
    echo "${TIMEPOINT}C2_read_depth control bam ${FILTERED_BAMDIR}/${TIMEPOINT}C2_to_pfal.50MAPQ.sorted.bam" >> ${OUTDIR}/${TIMEPOINT}_laptop_samples.txt
    echo "${TIMEPOINT}K1_read_depth knock-sideways bam ${FILTERED_BAMDIR}/${TIMEPOINT}K1_to_pfal.50MAPQ.sorted.bam" >> ${OUTDIR}/${TIMEPOINT}_laptop_samples.txt
    echo "${TIMEPOINT}K2_read_depth knock-sideways bam ${FILTERED_BAMDIR}/${TIMEPOINT}K2_to_pfal.50MAPQ.sorted.bam" >> ${OUTDIR}/${TIMEPOINT}_laptop_samples.txt

    # Generating bedmethyls:
    # TES change analysis (WAM change analysis)
    python3 ${RQC_PATH} approximate_tes -a ${ANNOTATION_FILE} --poly_a_filter ${POLY_A_FILTER} -i ${OUTDIR}/${TIMEPOINT}_laptop_samples.txt \
        --type mRNA -d ${READ_DEPTH} --compare_apa_between_treatments ${TIMEPOINT}C ${TIMEPOINT}K -p ${PADDING} \
        -o ${OUTDIR}/mrna_tes_analysis_${TIMEPOINT}hpi.tsv --exclude_contigs Pf3D7_API_v3 Pf3D7_MIT_v3

    python3 ${RQC_PATH} gene_methylation_analysis -a ${ANNOTATION_FILE}  --poly_a_filter ${POLY_A_FILTER} -i ${OUTDIR}/${TIMEPOINT}_laptop_samples.txt \
        --type mRNA -d ${READ_DEPTH} -r ${M6A_RATIO} --compare_methylation_between_treatments ${TIMEPOINT}C ${TIMEPOINT}K -p ${PADDING} \
        -o ${OUTDIR}/mRNA_methylation_analysis_${TIMEPOINT}hpi.tsv --exclude_contigs Pf3D7_API_v3 Pf3D7_MIT_v3

done