#!/bin/sh
set -e

source ./env.sh

# INPUTS: 
# - GFF

# OUTPUTS:
# - neighbour files

OUTDIR=$(pwd)/06_gene_neighbours_output
mkdir -p ${OUTDIR}

DISTANCES=("0" "100" "1000")

awk '$3 == "ncRNA_gene" || $3 == "protein_coding_gene" || $3 == "pseudogene"' ${ANNOTATION_FILE} | awk 'BEGIN{OFS="\t"} {print $1, $4-1, $5, $9, ".", $7, $3}' > ${OUTDIR}/plasmodium_genes.bed

for DIST in "${DISTANCES[@]}"; do
    bedtools window -sm -w $DIST -a ${OUTDIR}/plasmodium_genes.bed -b ${OUTDIR}/plasmodium_genes.bed \
        | awk '$4 != $11 {print $4}' | awk -F'[=;]' '{print $2}' \
        | sort -u \
        > ${OUTDIR}/genes_with_neighbour_${DIST}.txt

    grep -F -v -f ${OUTDIR}/genes_with_neighbour_${DIST}.txt ${OUTDIR}/plasmodium_genes.bed > ${OUTDIR}/plasmodium_isolated_genes_${DIST}.bed

done

