#!/usr/bin/env bash

source ./env.sh
set -e

# Define your input files
FILES=(
    "${BEDMETHYL_DIR}/28C1_to_pfal_0.95.0p.a.bed" 
    "${BEDMETHYL_DIR}/28C2_to_pfal_0.95.0p.a.bed" 
    "${BEDMETHYL_DIR}/28K1_to_pfal_0.95.0p.a.bed" 
    "${BEDMETHYL_DIR}/28K2_to_pfal_0.95.0p.a.bed"
)

# # Output directory
OUTDIR=$(pwd)/07_bedmethyl_feature_mapping_output
mkdir -p ${OUTDIR}

# awk '{print $3}' /Users/joshualevendis/Documents/RNA/honours/Pfalciparum3D7/gff/data/PlasmoDB-67_Pfalciparum3D7.gff | sort | uniq

# Extract relevant features from GFF
awk '$3 == "five_prime_UTR" {print $0}' ${ANNOTATION_FILE} > ${OUTDIR}/pfal_5p.gff
awk '$3 == "three_prime_UTR" {print $0}' ${ANNOTATION_FILE} > ${OUTDIR}/pfal_3p.gff
awk '$3 == "CDS" {print $0}' ${ANNOTATION_FILE} > ${OUTDIR}/pfal_cds.gff
awk '$3 == "ncRNA" {print $0}' ${ANNOTATION_FILE} > ${OUTDIR}/pfal_ncRNA.gff
awk '$3 == "rRNA" {print $0}' ${ANNOTATION_FILE} > ${OUTDIR}/pfal_rRNA.gff
awk '$3 == "tRNA" {print $0}' ${ANNOTATION_FILE} > ${OUTDIR}/pfal_tRNA.gff
awk '$3 == "snRNA" {print $0}' ${ANNOTATION_FILE} > ${OUTDIR}/pfal_snRNA.gff
awk '$3 == "snoRNA" {print $0}' ${ANNOTATION_FILE} > ${OUTDIR}/pfal_snoRNA.gff

awk '$3 == "mRNA" || $3 == "ncRNA_gene" {print $0}' ${ANNOTATION_FILE} > ${OUTDIR}/pfal_transcripts.gff

bedtools slop -i ${OUTDIR}/pfal_transcripts.gff -g ${GENOME_FAI_FILE} -b 500 > ${OUTDIR}/ex500_pfal_transcripts.gff
bedtools slop -i ${OUTDIR}/pfal_transcripts.gff -g ${GENOME_FAI_FILE} -b 1000 > ${OUTDIR}/ex1000_pfal_transcripts.gff

# Get list of mRNAs that overlap with another mRNA
bedtools intersect -a ${OUTDIR}/pfal_transcripts.gff -b ${OUTDIR}/pfal_transcripts.gff -wa -wb | awk -F '\t' '$4 != $13' > ${OUTDIR}/pfal_transcripts_overlaps.gff
bedtools intersect -a ${OUTDIR}/ex500_pfal_transcripts.gff -b ${OUTDIR}/ex500_pfal_transcripts.gff -wa -wb | awk -F '\t' '$4 != $13' > ${OUTDIR}/ex500_pfal_transcripts_overlaps.gff
bedtools intersect -a ${OUTDIR}/ex1000_pfal_transcripts.gff -b ${OUTDIR}/ex1000_pfal_transcripts.gff -wa -wb | awk -F '\t' '$4 != $13' > ${OUTDIR}/ex1000_pfal_transcripts_overlaps.gff

# Loop over each file
for f in "${FILES[@]}"; do
    echo "Processing $f ..."
    BASENAME=$(basename "$f")          # 28C1_to_pfal_0.95.0p.a.bed
    PREFIX=$(echo "$BASENAME" | cut -d'_' -f1)          # 28C1
    OUTFILE="${OUTDIR}/${PREFIX}_to_pfal_0.95.0p.a.feature_mapped.bed"
    
    # Perform the intersection with each feature file
    bedtools intersect -a "$f" -b "${OUTDIR}/pfal_5p.gff" -wa -c -s | \
    bedtools intersect -a - -b "${OUTDIR}/pfal_3p.gff" -wa -c -s | \
    bedtools intersect -a - -b "${OUTDIR}/pfal_cds.gff" -wa -c -s | \
    bedtools intersect -a - -b "${OUTDIR}/pfal_ncRNA.gff" -wa -c -s | \
    bedtools intersect -a - -b "${OUTDIR}/pfal_rRNA.gff" -wa -c -s | \
    bedtools intersect -a - -b "${OUTDIR}/pfal_tRNA.gff" -wa -c -s | \
    bedtools intersect -a - -b "${OUTDIR}/pfal_snRNA.gff" -wa -c -s | \
    bedtools intersect -a - -b "${OUTDIR}/pfal_snoRNA.gff" -wa -c -s > "$OUTFILE"

    echo "Output written to $OUTFILE"

    # Keep only sites which are not in overlapping mRNAs
    # ie genes which are far enough away from their neighbours
    bedtools intersect -a "$OUTFILE" -b "${OUTDIR}/pfal_transcripts_overlaps.gff" -v > "${OUTDIR}/${PREFIX}_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.bed"
    bedtools intersect -a "$OUTFILE" -b "${OUTDIR}/ex500_pfal_transcripts_overlaps.gff" -v > "${OUTDIR}/${PREFIX}_to_pfal_0.95.0p.a.feature_mapped.nonoverlap500.bed"
    bedtools intersect -a "$OUTFILE" -b "${OUTDIR}/ex1000_pfal_transcripts_overlaps.gff" -v > "${OUTDIR}/${PREFIX}_to_pfal_0.95.0p.a.feature_mapped.nonoverlap1000.bed"
done


# ----------- bedmethyl file preprocessing ----------- #

awk '$1 != "Pf3D7_MIT_v3" && $1 != "Pf3D7_API_v3"' ${OUTDIR}/28C1_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.bed > ${OUTDIR}/28C1_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.no_mito_api.bed
awk '$1 != "Pf3D7_MIT_v3" && $1 != "Pf3D7_API_v3"' ${OUTDIR}/28C2_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.bed > ${OUTDIR}/28C2_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.no_mito_api.bed
awk '$1 != "Pf3D7_MIT_v3" && $1 != "Pf3D7_API_v3"' ${OUTDIR}/28K1_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.bed > ${OUTDIR}/28K1_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.no_mito_api.bed
awk '$1 != "Pf3D7_MIT_v3" && $1 != "Pf3D7_API_v3"' ${OUTDIR}/28K2_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.bed > ${OUTDIR}/28K2_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.no_mito_api.bed

awk '$1 == "Pf3D7_MIT_v3"' ${OUTDIR}/28C1_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.bed > ${OUTDIR}/28C1_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.mito.bed
awk '$1 == "Pf3D7_MIT_v3"' ${OUTDIR}/28C2_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.bed > ${OUTDIR}/28C2_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.mito.bed
awk '$1 == "Pf3D7_MIT_v3"' ${OUTDIR}/28K1_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.bed > ${OUTDIR}/28K1_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.mito.bed
awk '$1 == "Pf3D7_MIT_v3"' ${OUTDIR}/28K2_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.bed > ${OUTDIR}/28K2_to_pfal_0.95.0p.a.feature_mapped.nonoverlap.mito.bed

echo "All files processed. Results in $OUTDIR/"
