#!/bin/bash

set -e

source ./env.sh
# source ${RQC_DIR}/env/bin/activate

# INPUTS: 
# - ${SAMPLE}_to_pfal.50MAPQ.sorted.bam
# - ${ANNOTATION}

# OUTPUTS:
# - ${SAMPLE}_to_pfal.50MAPQ.sorted.bam.featureCounts
# - ${SAMPLE}_to_pfal.50MAPQ.sorted.bam.featureCounts

PADDING=1000
READ_DEPTH=10
M6A_RATIO=0
POLY_A_FILTER=10
TES_DISTANCE_THRESHOLD=100

OUTDIR=$(pwd)/11_single_molecule_analysis_output
mkdir -p ${OUTDIR}

# IGV screenshot, hide small indels (<100bp), show m6A > 0.95p

# comparing all mod types
M6A_SAMPLES=${OUTDIR}/m6a_samples.txt
rm -f ${M6A_SAMPLES}
touch ${M6A_SAMPLES}
echo "28C1_read_depth control bam ${FILTERED_BAMDIR}/28C1_to_pfal.50MAPQ.sorted.bam" >> ${M6A_SAMPLES}
echo "28C2_read_depth control bam ${FILTERED_BAMDIR}/28C2_to_pfal.50MAPQ.sorted.bam" >> ${M6A_SAMPLES}
echo "28K1_read_depth knock-sideways bam ${FILTERED_BAMDIR}/28K1_to_pfal.50MAPQ.sorted.bam" >> ${M6A_SAMPLES}
echo "28K2_read_depth knock-sideways bam ${FILTERED_BAMDIR}/28K2_to_pfal.50MAPQ.sorted.bam" >> ${M6A_SAMPLES}
echo "28C1_m6A_0.95 control bedmethyl ${BEDMETHYL_DIR}/28C1_to_pfal_0.95.0p.a.bed" >> ${M6A_SAMPLES}
echo "28C2_m6A_0.95 control bedmethyl ${BEDMETHYL_DIR}/28C2_to_pfal_0.95.0p.a.bed" >> ${M6A_SAMPLES}
echo "28K1_m6A_0.95 knock-sideways bedmethyl ${BEDMETHYL_DIR}/28K1_to_pfal_0.95.0p.a.bed" >> ${M6A_SAMPLES}
echo "28K2_m6A_0.95 knock-sideways bedmethyl ${BEDMETHYL_DIR}/28K2_to_pfal_0.95.0p.a.bed" >> ${M6A_SAMPLES}

echo "32C1_read_depth control bam ${FILTERED_BAMDIR}/32C1_to_pfal.50MAPQ.sorted.bam" >> ${M6A_SAMPLES}
echo "32C2_read_depth control bam ${FILTERED_BAMDIR}/32C2_to_pfal.50MAPQ.sorted.bam" >> ${M6A_SAMPLES}
echo "32K1_read_depth knock-sideways bam ${FILTERED_BAMDIR}/32K1_to_pfal.50MAPQ.sorted.bam" >> ${M6A_SAMPLES}
echo "32K2_read_depth knock-sideways bam ${FILTERED_BAMDIR}/32K2_to_pfal.50MAPQ.sorted.bam" >> ${M6A_SAMPLES}
echo "32C1_m6A_0.95 control bedmethyl ${BEDMETHYL_DIR}/32C1_to_pfal_0.95.0p.a.bed" >> ${M6A_SAMPLES}
echo "32C2_m6A_0.95 control bedmethyl ${BEDMETHYL_DIR}/32C2_to_pfal_0.95.0p.a.bed" >> ${M6A_SAMPLES}
echo "32K1_m6A_0.95 knock-sideways bedmethyl ${BEDMETHYL_DIR}/32K1_to_pfal_0.95.0p.a.bed" >> ${M6A_SAMPLES}
echo "32K2_m6A_0.95 knock-sideways bedmethyl ${BEDMETHYL_DIR}/32K2_to_pfal_0.95.0p.a.bed" >> ${M6A_SAMPLES}

echo "36C1_read_depth control bam ${FILTERED_BAMDIR}/36C1_to_pfal.50MAPQ.sorted.bam" >> ${M6A_SAMPLES}
echo "36C2_read_depth control bam ${FILTERED_BAMDIR}/36C2_to_pfal.50MAPQ.sorted.bam" >> ${M6A_SAMPLES}
echo "36K1_read_depth knock-sideways bam ${FILTERED_BAMDIR}/36K1_to_pfal.50MAPQ.sorted.bam" >> ${M6A_SAMPLES}
echo "36K2_read_depth knock-sideways bam ${FILTERED_BAMDIR}/36K2_to_pfal.50MAPQ.sorted.bam" >> ${M6A_SAMPLES}
echo "36C1_m6A_0.95 control bedmethyl ${BEDMETHYL_DIR}/36C1_to_pfal_0.95.0p.a.bed" >> ${M6A_SAMPLES}
echo "36C2_m6A_0.95 control bedmethyl ${BEDMETHYL_DIR}/36C2_to_pfal_0.95.0p.a.bed" >> ${M6A_SAMPLES}
echo "36K1_m6A_0.95 knock-sideways bedmethyl ${BEDMETHYL_DIR}/36K1_to_pfal_0.95.0p.a.bed" >> ${M6A_SAMPLES}
echo "36K2_m6A_0.95 knock-sideways bedmethyl ${BEDMETHYL_DIR}/36K2_to_pfal_0.95.0p.a.bed" >> ${M6A_SAMPLES}


OUTPUT_FILE=${OUTDIR}/single_molecule_m6a_analysis.tsv
python3 ${RQC_PATH} m6A_tes_predictor_analysis -a ${ANNOTATION_FILE} -i ${M6A_SAMPLES} --type mRNA --exclude_contigs Pf3D7_API_v3 Pf3D7_MIT_v3 --poly_a_filter ${POLY_A_FILTER} -d ${READ_DEPTH} --offset_padding ${PADDING} --tes_distance_threshold ${TES_DISTANCE_THRESHOLD} --mod_ratio ${M6A_RATIO} -o ${OUTPUT_FILE}

Rscript R/m6A_tes_predictor_analysis.R ${OUTPUT_FILE} "28" "png" ${OUTDIR}
Rscript R/m6A_tes_predictor_analysis.R ${OUTPUT_FILE} "28" "pdf" ${OUTDIR}

Rscript R/m6A_tes_predictor_analysis.R ${OUTPUT_FILE} "32" "png" ${OUTDIR}
Rscript R/m6A_tes_predictor_analysis.R ${OUTPUT_FILE} "32" "pdf" ${OUTDIR}

Rscript R/m6A_tes_predictor_analysis.R ${OUTPUT_FILE} "36" "png" ${OUTDIR}
Rscript R/m6A_tes_predictor_analysis.R ${OUTPUT_FILE} "36" "pdf" ${OUTDIR}

